version: '3'

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - newsaggregator

    nginx:
        image: nginx:latest
        ports:
            - "8083:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - newsaggregator

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: symfony_db
            MYSQL_USER: symfony_user
            MYSQL_PASSWORD: symfony_password
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
        networks:
            - newsaggregator

networks:
    newsaggregator:
